spring:
  datasource:
    hash-datasource:
      url: ${SPRING_DATASOURCE_HASH_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_HASH_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_HASH_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    paste-datasource:
      url: ${SPRING_DATASOURCE_PASTE_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_PASTE_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASTE_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
