spring.datasource.url=jdbc:postgresql://localhost:5432/hash_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=hashUsername
spring.datasource.password=hashPassword

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
